# Generated by Django 4.1 on 2022-10-31 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="notes", name="user",),
    ]
